dataset_name: BTEDB_Abundances
columns:
  latitude: Latitude
  longitude: Longitude
  s_c: Cruise
  s_l: Line
  s_s: Station
pivot:
  cols:
  - Euphausia_brevis_adult_Abundance
  - Euphausia_brevis_calyptopis_Abundance
  - Euphausia_brevis_furcilia_Abundance
  - Euphausia_brevis_juvenile_Abundance
  - Euphausia_diomedeae_adult_Abundance
  - Euphausia_distinguenda_adult_Abundance
  - Euphausia_distinguenda_furcilia_Abundance
  - Euphausia_distinguenda_juvenile_Abundance
  - Euphausia_eximia_adult_Abundance
  - Euphausia_eximia_calyptopis_Abundance
  - Euphausia_eximia_calyptopis_C2_Abundance
  - Euphausia_eximia_calyptopis_C3_Abundance
  - Euphausia_eximia_damaged_Abundance
  - Euphausia_eximia_furcilia_Abundance
  - Euphausia_eximia_furcilia_F1_Abundance
  - Euphausia_eximia_furcilia_F2_Abundance
  - Euphausia_eximia_furcilia_F3_Abundance
  - Euphausia_eximia_furcilia_F4_Abundance
  - Euphausia_eximia_furcilia_F5_Abundance
  - Euphausia_eximia_furcilia_F6_Abundance
  - Euphausia_eximia_juvenile_Abundance
  - Euphausia_eximia_larvae_Abundance
  - Euphausia_gibboides_adult_Abundance
  - Euphausia_gibboides_calyptopis_Abundance
  - Euphausia_gibboides_calyptopis_C1_Abundance
  - Euphausia_gibboides_calyptopis_C2_Abundance
  - Euphausia_gibboides_calyptopis_C3_Abundance
  - Euphausia_gibboides_damaged_Abundance
  - Euphausia_gibboides_furcilia_Abundance
  - Euphausia_gibboides_furcilia_F1_Abundance
  - Euphausia_gibboides_furcilia_F2_Abundance
  - Euphausia_gibboides_furcilia_F3_Abundance
  - Euphausia_gibboides_furcilia_F4_Abundance
  - Euphausia_gibboides_furcilia_F5_Abundance
  - Euphausia_gibboides_furcilia_F6_Abundance
  - Euphausia_gibboides_juvenile_Abundance
  - Euphausia_gibboides_larvae_Abundance
  - Euphausia_hemigibba_adult_Abundance
  - Euphausia_hemigibba_calyptopis_Abundance
  - Euphausia_hemigibba_furcilia_Abundance
  - Euphausia_hemigibba_juvenile_Abundance
  - Euphausia_lamelligera_adult_Abundance
  - Euphausia_mutica_adult_Abundance
  - Euphausia_mutica_calyptopis_Abundance
  - Euphausia_mutica_furcilia_Abundance
  - Euphausia_mutica_juvenile_Abundance
  - Euphausia_pacifica_adult_Abundance
  - Euphausia_pacifica_calyptopis_Abundance
  - Euphausia_pacifica_calyptopis_C1_Abundance
  - Euphausia_pacifica_calyptopis_C2_Abundance
  - Euphausia_pacifica_calyptopis_C3_Abundance
  - Euphausia_pacifica_damaged_Abundance
  - Euphausia_pacifica_furcilia_Abundance
  - Euphausia_pacifica_furcilia_F1_Abundance
  - Euphausia_pacifica_furcilia_F2_Abundance
  - Euphausia_pacifica_furcilia_F3_Abundance
  - Euphausia_pacifica_furcilia_F4_Abundance
  - Euphausia_pacifica_furcilia_F5_Abundance
  - Euphausia_pacifica_furcilia_F6_Abundance
  - Euphausia_pacifica_furcilia_F7_Abundance
  - Euphausia_pacifica_juvenile_Abundance
  - Euphausia_pacifica_larvae_Abundance
  - Euphausia_pacifica_metanauplius_Abundance
  - Euphausia_recurva_adult_Abundance
  - Euphausia_recurva_calyptopis_Abundance
  - Euphausia_recurva_calyptopis_C1_Abundance
  - Euphausia_recurva_calyptopis_C2_Abundance
  - Euphausia_recurva_calyptopis_C3_Abundance
  - Euphausia_recurva_damaged_Abundance
  - Euphausia_recurva_furcilia_Abundance
  - Euphausia_recurva_furcilia_F1_Abundance
  - Euphausia_recurva_furcilia_F2_Abundance
  - Euphausia_recurva_furcilia_F3_Abundance
  - Euphausia_recurva_furcilia_F4_Abundance
  - Euphausia_recurva_furcilia_F5_Abundance
  - Euphausia_recurva_furcilia_F6_Abundance
  - Euphausia_recurva_juvenile_Abundance
  - Euphausia_recurva_metanauplius_Abundance
  - Euphausia_tenera_adult_Abundance
  - Euphausia_tenera_furcilia_Abundance
  - Euphausia_tenera_juvenile_Abundance
  - Nematobrachion_boopis_adult_Abundance
  - Nematobrachion_boopis_furcilia_Abundance
  - Nematobrachion_boopis_juvenile_Abundance
  - Nematobrachion_flexipes_adult_Abundance
  - Nematobrachion_flexipes_calyptopis_Abundance
  - Nematobrachion_flexipes_furcilia_Abundance
  - Nematobrachion_flexipes_juvenile_Abundance
  - Nematobrachion_flexipes_larvae_Abundance
  - Nematoscelis_atlantica_adult_Abundance
  - Nematoscelis_atlantica_calyptopis_Abundance
  - Nematoscelis_atlantica_furcilia_Abundance
  - Nematoscelis_atlantica_juvenile_Abundance
  - Nematoscelis_difficilis_adult_Abundance
  - Nematoscelis_difficilis_calyptopis_Abundance
  - Nematoscelis_difficilis_calyptopis_C1_Abundance
  - Nematoscelis_difficilis_calyptopis_C2_Abundance
  - Nematoscelis_difficilis_calyptopis_C3_Abundance
  - Nematoscelis_difficilis_damaged_Abundance
  - Nematoscelis_difficilis_furcilia_Abundance
  - Nematoscelis_difficilis_furcilia_F1_Abundance
  - Nematoscelis_difficilis_furcilia_F2_Abundance
  - Nematoscelis_difficilis_furcilia_F3_Abundance
  - Nematoscelis_difficilis_juvenile_Abundance
  - Nematoscelis_difficilis_larvae_Abundance
  - Nematoscelis_difficilis_metanauplius_Abundance
  - Nematoscelis_gracilis_adult_Abundance
  - Nematoscelis_gracilis_furcilia_Abundance
  - Nematoscelis_gracilis_juvenile_Abundance
  - Nematoscelis_microps_adult_Abundance
  - Nematoscelis_microps_juvenile_Abundance
  - Nematoscelis_tenella_adult_Abundance
  - Nematoscelis_tenella_calyptopis_Abundance
  - Nematoscelis_tenella_furcilia_Abundance
  - Nematoscelis_tenella_juvenile_Abundance
  - Nematoscelis_tenella_larvae_Abundance
  - Nyctiphanes_simplex_adult_Abundance
  - Nyctiphanes_simplex_calyptopis_Abundance
  - Nyctiphanes_simplex_calyptopis_C1_Abundance
  - Nyctiphanes_simplex_calyptopis_C2_Abundance
  - Nyctiphanes_simplex_calyptopis_C3_Abundance
  - Nyctiphanes_simplex_damaged_Abundance
  - Nyctiphanes_simplex_furcilia_Abundance
  - Nyctiphanes_simplex_furcilia_F1_Abundance
  - Nyctiphanes_simplex_furcilia_F2_Abundance
  - Nyctiphanes_simplex_furcilia_F3_Abundance
  - Nyctiphanes_simplex_furcilia_F4_Abundance
  - Nyctiphanes_simplex_furcilia_F5_Abundance
  - Nyctiphanes_simplex_furcilia_F6_Abundance
  - Nyctiphanes_simplex_juvenile_Abundance
  - Nyctiphanes_simplex_larvae_Abundance
  - Nyctiphanes_simplex_metanauplius_Abundance
  - Stylocheiron_abbreviatum_adult_Abundance
  - Stylocheiron_abbreviatum_calyptopis_Abundance
  - Stylocheiron_abbreviatum_furcilia_Abundance
  - Stylocheiron_abbreviatum_juvenile_Abundance
  - Stylocheiron_abbreviatum_larvae_Abundance
  - Stylocheiron_affine_adult_Abundance
  - Stylocheiron_affine_calyptopis_Abundance
  - Stylocheiron_affine_furcilia_Abundance
  - Stylocheiron_affine_juvenile_Abundance
  - Stylocheiron_carinatum_adult_Abundance
  - Stylocheiron_carinatum_calyptopis_Abundance
  - Stylocheiron_carinatum_furcilia_Abundance
  - Stylocheiron_carinatum_juvenile_Abundance
  - Stylocheiron_maximum_adult_Abundance
  - Stylocheiron_maximum_calyptopis_Abundance
  - Stylocheiron_maximum_furcilia_Abundance
  - Stylocheiron_maximum_juvenile_Abundance
  - Stylocheiron_maximum_larvae_Abundance
  - Stylocheiron_suhmi_adult_Abundance
  - Stylocheiron_suhmi_calyptopis_Abundance
  - Stylocheiron_suhmi_furcilia_Abundance
  - Stylocheiron_suhmi_juvenile_Abundance
  - Thysanoessa_gregaria_adult_Abundance
  - Thysanoessa_gregaria_calyptopis_Abundance
  - Thysanoessa_gregaria_calyptopis_C1_Abundance
  - Thysanoessa_gregaria_calyptopis_C2_Abundance
  - Thysanoessa_gregaria_calyptopis_C3_Abundance
  - Thysanoessa_gregaria_damaged_Abundance
  - Thysanoessa_gregaria_furcilia_Abundance
  - Thysanoessa_gregaria_furcilia_F1_Abundance
  - Thysanoessa_gregaria_furcilia_F2_Abundance
  - Thysanoessa_gregaria_furcilia_F3_Abundance
  - Thysanoessa_gregaria_furcilia_F4_Abundance
  - Thysanoessa_gregaria_furcilia_F5_Abundance
  - Thysanoessa_gregaria_furcilia_F6_Abundance
  - Thysanoessa_gregaria_juvenile_Abundance
  - Thysanoessa_gregaria_larvae_Abundance
  - Thysanoessa_spinifera_adult_Abundance
  - Thysanoessa_spinifera_calyptopis_Abundance
  - Thysanoessa_spinifera_calyptopis_C1_Abundance
  - Thysanoessa_spinifera_calyptopis_C2_Abundance
  - Thysanoessa_spinifera_calyptopis_C3_Abundance
  - Thysanoessa_spinifera_damaged_Abundance
  - Thysanoessa_spinifera_furcilia_Abundance
  - Thysanoessa_spinifera_furcilia_F1_Abundance
  - Thysanoessa_spinifera_furcilia_F2_Abundance
  - Thysanoessa_spinifera_furcilia_F3_Abundance
  - Thysanoessa_spinifera_furcilia_F4_Abundance
  - Thysanoessa_spinifera_furcilia_F5_Abundance
  - Thysanoessa_spinifera_furcilia_F6_Abundance
  - Thysanoessa_spinifera_juvenile_Abundance
  - Thysanoessa_spinifera_larvae_Abundance
  - Thysanoessa_spinifera_metanauplius_Abundance
  - Thysanopoda_cornuta_furcilia_Abundance
  - Thysanopoda_egregia_calyptopis_Abundance
  - Thysanopoda_egregia_furcilia_Abundance
  - Thysanopoda_egregia_juvenile_Abundance
  - Thysanopoda_monacantha_adult_Abundance
  - Thysanopoda_monacantha_calyptopis_Abundance
  - Thysanopoda_monacantha_furcilia_Abundance
  - Thysanopoda_monacantha_juvenile_Abundance
  - Thysanopoda_obtusifrons_adult_Abundance
  - Thysanopoda_obtusifrons_calyptopis_Abundance
  - Thysanopoda_obtusifrons_furcilia_Abundance
  - Thysanopoda_obtusifrons_juvenile_Abundance
  - Thysanopoda_orientalis_adult_Abundance
  - Thysanopoda_orientalis_calyptopis_Abundance
  - Thysanopoda_orientalis_furcilia_Abundance
  - Thysanopoda_orientalis_juvenile_Abundance
  - Thysanopoda_pectinata_calyptopis_Abundance
  - Thysanopoda_pectinata_furcilia_Abundance
  - Thysanopoda_pectinata_juvenile_Abundance
  names_to: taxon
  values_to: abundance
time:
  type: date
  column: Date
